const actionTypes = {
    ADD_EXPENSES: 'ADD_EXPENSES',
    DELETE_EXPENSES: 'DELETE_EXPENSES',
    CLEAR_EXPENSE: 'CLEAR_EXPENSE',
    UPDATE_SHAREACCOUNT: 'UPDATE_SHAREACCOUNT',
    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT'
}
export default actionTypes;